# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gedSzN4kzgoCZ9mv4nUfVKGFip8V0QIg
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_excel(list(uploaded.keys())[0])

df.head()

# Task 1: Load and Explore the Dataset

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay

# Load Excel dataset
df = pd.read_excel("spam .xlsx")

# Display first 5 rows
print("First 5 Rows:")
display(df.head())

# Number of rows and columns
print("\nDataset Shape:")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Count Ham and Spam
print("\nMessage Counts:")
print(df["Category"].value_counts())

# Task 2: Visualize Ham vs Spam Messages

message_counts = df["Category"].value_counts()

plt.figure(figsize=(7, 5))

plt.bar(message_counts.index, message_counts.values)

plt.title("Number of Spam vs Ham Messages")
plt.xlabel("Message Type")
plt.ylabel("Number of Messages")

plt.show()

# Find which type is more common
most_common = message_counts.idxmax()
most_common_count = message_counts.max()

print("Most common message type:", most_common)
print("Number of messages:", most_common_count)

# Task 3: Prepare the Data

df["Category"] = df["Category"].map({
    "ham": 0,
    "spam": 1
})

# Separate X and y
X = df["Message"]
y = df["Category"]

print("X (Messages):")
print(X.head())

print("\ny (Labels):")
print(y.head())

# Task 4: Split the Dataset

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

# Make sure all text data is string
X_train = X_train.fillna('').astype(str)
X_test = X_test.fillna('').astype(str)

# Create vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

# Training data
X_train_vectorized = vectorizer.fit_transform(X_train)

# Testing data
X_test_vectorized = vectorizer.transform(X_test)

print("Training shape:", X_train_vectorized.shape)
print("Testing shape:", X_test_vectorized.shape)

# Task 6: Train Machine Learning Model

model = LogisticRegression(max_iter=1000)

# Train the model
model.fit(X_train_vectorized, y_train)

print("Model training completed successfully!")

# Task 7: Make Predictions

predictions = model.predict(X_test_vectorized)

print("Predictions:")
print(predictions[:20])

# Task 8: Calculate Accuracy

accuracy = accuracy_score(y_test, predictions)

print("Model Accuracy:", accuracy)
print("Model Accuracy (%):", accuracy * 100)

# Number of correctly classified messages

correct_predictions = (predictions == y_test).sum()

print("Correctly Classified Messages:", correct_predictions)
print("Total Test Messages:", len(y_test))

# Task 9: Test Your Own SMS

new_message = input("Enter an SMS message: ")

# Convert the new message using the SAME vectorizer
new_message_vectorized = vectorizer.transform([new_message])

# Predict
prediction = model.predict(new_message_vectorized)[0]

# Display result
if prediction == 0:
    print("\n📩 HAM MESSAGE")
else:
    print("\n🚨 SPAM MESSAGE")

